### ISSUE TITLE
Lack of configuration for Laravel

### ISSUE THREAD

**Issue by quantrung9** [arubacao/php-cs-fixer-config#1]
Hi @arubacao 

I have just compared https://github.com/laravel/framework/blob/5.4/.php_cs and your Laravel configuration (https://github.com/arubacao/php-cs-fixer-config/blob/master/src/Laravel.php). Your configuration doesn't have some rules like Laravel .php_cs had:

- **phpdoc_no_access**
- **phpdoc_no_package**
- short_echo_tag (**no_short_echo_tag** in CS 2.0)

And for the @PSR2, you don't have this rule: **no_break_comment**

**Comment by quantrung9** [comment]
@arubacao Do you think we should add these rules?

**Comment by arubacao** [comment]
Hey @toolowner 
I must have missed your issue.
523f504c912bcf9fd8e1c40ec45e2d057f1d4a86 and a266458258dca8c23c15fe6d1facbfd8c40ef122 closes this.

**Comment by quantrung9** [comment]
Thanks @arubacao
